### ISSUE TITLE
Permissions system for documents on a per-document basis

### ISSUE THREAD

**Issue by klstilling** [connors511/dinto-issues#1]
Some sort of permission system, where you can exclude members from editing/writing documents to prevent abuse etc. This exclusion can either be on a per-document basis or globally from the entire community.

**Comment by jonaslb** [comment]
Suggest that this be called "Permissions system for documents on a per-document basis" because I think I detailed the version control part better in #4 :)

**Comment by klstilling** [comment]
Fixed.

**Comment by connors511** [comment]
I'm thinking that by default, all documents are writable by everyone.
Document creator and community administrators are able to enable 'restricted writes' to the document by selectively picking the users who should be able to edit the document.
Community administrators would also be able to disallow the creator to edit the document.
Thoughts?

**Comment by klstilling** [comment]
Yes, that sounds like a good idea, I guess the system will be similar to the old dinner-club participant system. Let the front-end have a button which deselects everyone but yourself and the community administrators. That would be quite handy imo.
