### ISSUE TITLE
Create multiple events at once 

### ISSUE THREAD

**Issue by adambaxter91** [connors511/dinto-issues#27]
It would be a nice feature if you could make multiple events at once. Like if you could make an event and set it to occur once every week.

**Comment by connors511** [comment]
@adambaxter91 with an end date? Or would you want it to repeat indefinitely?
We're just talking an exactly copy of an event (title, desciption, organizers, ...), just duplicated to another date, yes?

**Comment by adambaxter91** [comment]
End date would be a nice feature. And yes an exact copy is what i was thinking
