### ISSUE TITLE
Strange message when updating event title

### ISSUE THREAD

**Issue by adambaxter91** [connors511/dinto-issues#31]
I get these two messages when i update my event title
![screenshot from 2017-03-06 18-26-33](https://cloud.githubusercontent.com/assets/12399429/23621195/0142cd96-029a-11e7-9011-2fb259453ec4.png)

**Comment by connors511** [comment]
"Changed title" and "Changed slug" ?

**Comment by adambaxter91** [comment]
Yes, what is slug?

**Comment by connors511** [comment]
The title converted to a URL friendly name, to be used as a readable link, i.e. `/community/events/1-to-be-announced` vs `/community/events/1`

**Comment by adambaxter91** [comment]
I see
