### ISSUE TITLE
Search phrase is not deleted after user selection under Accounting->Manage Community->Manage Balance of Users

### ISSUE THREAD

**Issue by jonaslb** [connors511/dinto-issues#33]
For example, I want to find Adam. I type "ada" and choose Adam from the list. Adam then appears in the list of users to be affected, but the search phrase is still there. It should probably be deleted automatically after selection of a user.

**Comment by connors511** [comment]
I'm not sure I'd label this as a bug, as that particular field allows for managing the balance of multiple users at the same time, thus I'd be beneficial to keep the query if you were to manage Adam and Adamine, yes.

**Comment by jonaslb** [comment]
Rarely do multiple users withdraw/deposit the same amount though (and even if they do, they don't share their first names). I find that I usually have to do each one individually, and then the multi-selection is mostly in the way.
