### ISSUE TITLE
Ability for members to view others' transactions under Accounting -> Transactions

### ISSUE THREAD

**Issue by jonaslb** [connors511/dinto-issues#35]
The table under Transactions only shows one's own transactions. This is a good default, but it should be possible for anyone to see all transactions. Perhaps in the same manner that an admin can under Manage Community (except with an applied filter to begin with).

I think it might be possible for members to view their own and others' transactions under Accounting -> Reports and then clicking the numbers. At least I can, but then I'm the admin. So this feature is not super critical but I think it seems natural to enable this. The transactions are not secret, after all.

**Comment by connors511** [comment]
All members are able to view transactions by clicking on the numbers in a report, there's no restrictions on that.
Will look into adding community transactions to the "Transaction" tab as well.
