### ISSUE TITLE
News stream sorting puts events in the far future at the top, near future at the bottom

### ISSUE THREAD

**Issue by jonaslb** [connors511/dinto-issues#37]
It would probably make sense if events in the near future (most immediately relevant) were at the top.

**Comment by connors511** [comment]
I've considered something similar to Facebook; Newest, Last updated, Coming up..
Alternatively, something smart like a prio list;
* Happening within 3 days
* Updated in the past week
* Created within the past week
* Happening in 4-7 days
* Updated more than a week ago
* Created more than a week ago
* Happening in more than a week

All of above, merged seamlesssly into a single stream.. Might be overkill tho

**Comment by jonaslb** [comment]
You could just make two lists for everything; future and past (maybe call them something else). The future would sort by time ascending (eg. events), and the past by time descending (eg. edited docs/closed events).
