### ISSUE TITLE
Simple version control on documents

### ISSUE THREAD

**Issue by jonaslb** [connors511/dinto-issues#4]
There should be a simple version control on documents.

If someone can edit a document without it being visible to anyone, the document system becomes unreliable for trusted documents. 

For example, someone might edit a meeting minute (hedder et referat virkelig det???) to be favorable to their personal opinion, even though an opposing decision was made at the meeting. And later, when someone returns to the document again to remember what happened, they would be clueless that it had been edited.

A first "version of version control" could just be an edit history of when someone edited it. 
But optimally it would show differences for each edit.

**Comment by connors511** [comment]
Referat = Summary.
By version control, what would you prefer; git-like diff'ing or just a "document looked like this at revision X"?

**Comment by jonaslb** [comment]
Obviously git(hub)-like is superior :-P
