### ISSUE TITLE
Buttons and examples for markdown editing

### ISSUE THREAD

**Issue by jonaslb** [connors511/dinto-issues#46]
Supposedly, from what I hear, plaintext editing and markdown is "too hard". I don't agree but we discussed that buttons for eg. headers (because hashtag is the least obvious feature of md) might be a good idea. 

One way to help people into md might just be a default text when you create a new document that would contain an example of the basic md features (headers, bold, cursive, itemize/enumerate lists).

**Comment by jonaslb** [comment]
an idea
<https://gist.github.com/jonaslb/5c04d2fa58d9ab99397be3b3152b2f5b>

**Comment by connors511** [comment]
A WYSIWYG editor is coming in the next release.
