### ISSUE TITLE
Transactions show "no transactions have been created yet"

### ISSUE THREAD

**Issue by jonaslb** [connors511/dinto-issues#48]
.. when in fact there has.

Both accounting->transactions and accounting->manage community does this. It is still possible to see transactions by clicking the numbers in accounting reports.

It may be related to me deleting a member? Because I just did that and it seemed to maybe start after that.

(happens on both chrome and firefox)

**Comment by connors511** [comment]
@jonaslb I believe its caused by the lists trying to render the profile image of a community member that's no longer in the community.
Will fix in next release.
