### ISSUE TITLE
Currency should be selectable in community settings

### ISSUE THREAD

**Issue by jonaslb** [connors511/dinto-issues#5]
As the title says. Currently we are forced to look at €-symbols. Clearly, " kr." is the superior currency.  

Further in danish, we usually put the currency after the amount, eg. "10 kr.". This should probably also be an option.

**Comment by jonaslb** [comment]
@connors511 This was closed a long time ago but does not seem to have ever made it to production. So it's still ongoing?

**Comment by connors511** [comment]
It's not directly selectable, but it selects the currency based on the users country, unless the community has a billing address set (required when subscribing to a plan) to ensure all users in the same community has the same currency.
I can see I made a minor derp in that logic however -- a fix for this will be deployed asap :)
