### ISSUE TITLE
Amount in notifications is off by a factor of 100

### ISSUE THREAD

**Issue by klstilling** [connors511/dinto-issues#52]
When opening the notifications pane, all amounts are off by a factor of 100 (244DKK shows as 2.44 EUR).

**Comment by connors511** [comment]
@klstilling Can you confirm is this is fixed, or if its still an active issue?

**Comment by klstilling** [comment]
The issue appears to have been fixed after a recent update. New notifications are not off by a factor of 100. Closing.
