### ISSUE TITLE
Document category icons are impossible to go through

### ISSUE THREAD

**Issue by jonaslb** [connors511/dinto-issues#53]
While it's possible to search, it's difficult to find out whether anything of the kind you are looking for exists. 
For example, I was looking for something like a bottle or beer can/cup, but had to use a coffee cup because that's what came up under "cup". It should be possible to show the 700-something icons so that one could scroll through them instead and see if something looked right.

**Comment by connors511** [comment]
@jonaslb You are absolutely right. I'll try to come up with an improved interface somehow.
In the meantime you can browse all the icons at http://fontawesome.io/icons/
