### ISSUE TITLE
Documents titles are shortened 

### ISSUE THREAD

**Issue by jonaslb** [connors511/dinto-issues#55]
Documents titles are shortened. For example, `Effektiv, korrekt havregrød ` becomes `Effektiv, korrekt`. 

Clearly it should show the entire title.

Another option is to at indicate that the title was shortened by for example 3 dots. I don't like that though, because what's the point of showing the title then.

**Comment by connors511** [comment]
@jonaslb This is just on the document overview, right?

**Comment by jonaslb** [comment]
Yes
