### ISSUE TITLE
When loading an auto-saved document, the title and category should be loaded in addition to content

### ISSUE THREAD

**Issue by klstilling** [connors511/dinto-issues#57]

**Comment by connors511** [comment]
This is caused by the auto-save feature currently only saving the content of the document, not the title nor category. Auto-save could be extended to save those as well tho.
Would you like that?

**Comment by klstilling** [comment]
Auto-saving the document title would be neat, and category aswell if not too much hassle, but not strictly needed, although I think most other people will wonder why it is not auto-saving the category if it saves the title and contents.

**Comment by connors511** [comment]
Ill mark this as an enhancement rather than a bug then. Setting the title to "New document" in your case, was/is due to the fact, that auto-save is currently only saving the document body, and no the title and category. I'll take a swing at those in the near future.
