### ISSUE TITLE
Event activity descriptions are inconsistent and sometimes missing

### ISSUE THREAD

**Issue by jonaslb** [connors511/dinto-issues#59]
[This](https://din.to/community/events/14-test) event is an example. Some activity items are bullet points, others are not.
Further there is an activity description which seems to be missing. This one however is likely coinciding with the buggyness of event activities in general (i expect kls is making a bug about that).

**Comment by connors511** [comment]
I've explained why some are bullets and some are not in #60.
I'm closing this as resolved for the missing and buggy descriptions and keeping #60 open for a discussion on how to handle the bullet points.
