### ISSUE TITLE
Transactions under accounting should show all details

### ISSUE THREAD

**Issue by jonaslb** [connors511/dinto-issues#6]
Accounting -> Transactions currently does not show the transaction commentary (eg from a manually created fee, fine or deposit/withdrawal). It should. The same goes for the table under Accounting -> Manage Community.

**Comment by connors511** [comment]
I'll consider this issue, as an issue for showing comments on transactions.
Please create a seperate issue, if you'd like the "Transaction" tab to show community transaction in addition to your own.
