### ISSUE TITLE
Event time-format is difficult to read.

### ISSUE THREAD

**Issue by klstilling** [connors511/dinto-issues#65]
The time format is currently printed as "2017-04-15 01:59:00" in the activities of an event.
1. I feel that having seconds in the time is pointless
2. I think that the way the date is printed is difficult to read. It will be easier on the eyes if it is printed in the format 15th of April '17, 2PM -- or something like that.
3. Why include the year? You can usually deduce the year of the deadline from the year that the event is held.

**Comment by connors511** [comment]
@klstilling where do you find this date string?
Did you get it from [this event](https://din.to/community/events/15-paaskefrokost), when Lars Holm changed the deadline?

**Comment by klstilling** [comment]
@connors511 yes, that is the event I am referring to.

**Comment by connors511** [comment]
@klstilling Would you prefer if changes to the `date` field also had a more speech-like format like `Changed date from 15th of April to 17th of April` instead of `Changed date from 2017-04-15 to 2017-04-17` ?

**Comment by klstilling** [comment]
Yes. It would be lovely if the dates and times on the entire site used this format. I will reopen this issue if I find any inconsistencies elsewhere on the site.
