### ISSUE TITLE
Create "Community waiver" and "Donation" transaction types

### ISSUE THREAD

**Issue by jonaslb** [connors511/dinto-issues#76]
First of all this is not acute for our community but it's something that I think might be relevant.

These types would be listed under "transactions" in reports together with deposit/withdraw. "Community waiver" would function just like "deposit", and "Donation" would function just like "withdraw", in that an amount is transferred to/from the users account. The only difference is that they don't involve cash. 

In a way they would be like "transfers" but instead of between users, it would be between the community and a user (creatable by admins).

**Comment by connors511** [comment]
A user create-able version of the transactions Dinto automatically creates when a user leaves the community with a non-zero balance, right?
