### ISSUE TITLE
Successfully creating an event does not redirect to the event calendar

### ISSUE THREAD

**Issue by klstilling** [connors511/dinto-issues#82]
Read the title

**Comment by connors511** [comment]
@klstilling do you expect it to redirect to calendar when creating an event, rather than opening the event in view-mode?

**Comment by klstilling** [comment]
@connors511 actually I did not get redirected at all. I assumed that the calendar was the view I would get redirected to, but the event view is also fine I guess.

**Comment by connors511** [comment]
@klstilling can you provide steps to reproduce?
I'm consistently being redirected to the event view as expected -- let me know if you'd like to be redirected to the calendar view again instead.
